routes/web.php
<?php

use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\ReminderController;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BoardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


// TODOList routes
Route::name('boards.')->prefix('boards')->group(function () {
    // Boards routes
    Route::get('/', [BoardController::class, 'index'])->name('index');
    Route::get('/create', [BoardController::class, 'create'])->name('create');
    Route::post('/', [BoardController::class, 'store'])->name('store');
    Route::get('/{id}/edit', [BoardController::class, 'edit'])->name('edit');
    Route::put('/{id}', [BoardController::class, 'update'])->name('update');
    Route::delete('/{id}', [BoardController::class, 'destroy'])->name('destroy');

    // Tasks routes
    Route::name('tasks.')->prefix('{board_id}/tasks')->group(function () {
        Route::get('/create', [TaskController::class, 'create'])->name('create');
        Route::post('/', [TaskController::class, 'store'])->name('store');
        Route::get('/{id}/edit', [TaskController::class, 'edit'])->name('edit');
        Route::put('/{id}', [TaskController::class, 'update'])->name('update');
        Route::delete('/{id}', [TaskController::class, 'destroy'])->name('destroy');
    });
});


// Reminder routes
Route::name('reminders.')->prefix('reminders')->group(function () {
    Route::get('/', [ReminderController::class, 'index'])->name('index');
});


// Calendar routes
Route::name('calendar.')->prefix('calendar')->group(function () {
   Route::get('/', [CalendarController::class, 'index'])->name('index');
});


// Profile routes
Route::name('profile.')->prefix('profile')->middleware('auth')->group(function () {
    Route::get('/', [RegisteredUserController::class, 'index'])->name('index');
    Route::get('/editNameAndEmail', [RegisteredUserController::class, 'editNameAndEmail'])->name('editNameAndEmail');
    Route::get('/editPassword', [RegisteredUserController::class, 'editPassword'])->name('editPassword');
    Route::put('/updatePassword', [RegisteredUserController::class, 'updatePassword'])->name('updatePassword');
    Route::put('/updateEmailAndName', [RegisteredUserController::class, 'updateNameAndEmail'])->name('updateNameAndEmail');
});

require __DIR__.'/auth.php';

app/Models/Board.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Board extends Model
{
    use HasFactory;

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function tasks()
    {
        return $this->hasMany(Task::class, 'board_id');
    }
}

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    public function board()
    {
        return $this->belongsTo(Board::class, 'board_id');
    }

    public function isSetReminder() {
        return $this->notify;
    }

    public function isCompleted() {
        return $this->status === 'completed';
    }

}

app/Http/Controllers/BoardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Board;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BoardController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $user = Auth::user();
        return view('boards.index', ['boards' => $user->boards]);
    }

    public function create()
    {
        return view('boards.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:255',
                           ]);

        $board = new Board();
        $board->name = $request->input('name');
        $board->color = $request->input('color');
        $board->user_id = Auth::id();
        $board->save();

        return redirect()->route('boards.index');
    }

    public function edit($id)
    {
        $board = Board::find($id);
        return view('boards.edit', ['board' => $board]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required'
                           ]);

        $board = Board::find($id);
        $board->name = $request->input('name');
        $board->color = $request->input('color');
        $board->save();

        return redirect()->route('boards.index');
    }

    public function destroy($id)
    {
        $board = Board::find($id);
        $tasks = $board->tasks;
        foreach ($tasks as $task) {
            $task->delete();
        }
        $board->delete();

        return redirect()->route('boards.index');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Board;
use App\Models\Task;
use Carbon\Carbon;
use Illuminate\Http\Request;


class TaskController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function create($board_id)
    {
        $board = Board::find($board_id);
        return view('boards.tasks.create', ['board' => $board]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|max:255',
            'description' => 'required|max:255',
            'deadline' => 'required',
            'board_id' => 'required'
                           ]);

        $task = new Task();
        $task->title = $request->input('title');
        $task->description = $request->input('description');
        $task->deadline = $request->input('deadline');
        $task->board_id = $request->input('board_id');
        $task->save();

        return redirect()->route('boards.index');
    }

    public function edit($board_id, $id)
    {
        $task = Task::find($id);
        return view('boards.tasks.edit', ['task' => $task]);
    }

    public function update(Request $request, $board_id, $id)
    {
        $request->validate([
            'title' => 'required|max:255',
            'description' => 'required|max:255',
            'deadline' => 'required',
                           ]);

        $task = Task::find($id);
        $task->title = $request->input('title');
        $task->description = $request->input('description');
        $task->status = $request->input('status');
        $task->deadline = $request->input('deadline');
        if ($request->has('notify')) {
            $task->notify = $request->input('notify');
        }

        if ($request->input('status') === 'completed') {
            $task->completion_date = Carbon::now();
        }
        $task->save();

        return redirect()->route('boards.index');
    }

    public function destroy($board_id, $id)
    {
        $task = Task::find($id);
        $task->delete();
        return redirect()->route('boards.index');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/boards/tasks/create.blade.php
<x-app-layout>
    <x-slot name="header">
        Создание задачи для доски {{ $board->name }}
    </x-slot>


    <div class="m-10 p-10 max-w-sm mx-auto bg-white rounded-xl shadow-md flex-column space-y-4 items-center space-x-4">

        <!--Ошибки ввода-->
        @if ($errors->any())
            <div class="alert">
                <ul class="list-disc">
                    @foreach ($errors->all() as $error)
                        <li class="text-red-700">{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div>
            <form action="{{ route('boards.tasks.store', $board->id) }}" method="POST" class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                @csrf
                <div class="flex-shrink-0">

                    <div>
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="task">Загловок задачи</label>
                        <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" id="inline-full-name" type="text" name="title">
                    </div>

                    <div class="mt-10">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="task">Описание задачи</label>
                        <p><textarea class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" id="inline-full-name" rows="10" cols="45" name="description"></textarea></p>
                    </div>

                    <div class="mt-10">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="task">Deadline</label>
                        <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" type="date" name="deadline">
                    </div>

                    <div class="mt-10">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="task">Status</label>
                        <select class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" name="status" size="1">
                            <option value="incomplete">Не готова</option>
                            <option value="completed">Готова</option>
                        </select>
                    </div>

                    <input type="hidden" name="board_id" value="{{ $board->id }}">

                    <button class="mt-10 py-2 px-4 font-semibold rounded-lg shadow-md text-white bg-green-500 hover:bg-green-700" type="submit">
                        Создать
                    </button>

                </div>
            </form>
        </div>

    </div>

</x-app-layout>

resources/views/boards/tasks/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        Создание задачи для доски {{ $task->board->name }}
    </x-slot>

    <div class="m-10 p-10 max-w-sm mx-auto bg-white rounded-xl shadow-md flex-column space-y-4 items-center space-x-4">

        <!--Ошибки ввода-->
        @if ($errors->any())
            <div class="alert">
                <ul class="list-disc">
                    @foreach ($errors->all() as $error)
                        <li class="text-red-700">{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div>
            <form action="{{ route('boards.tasks.update', [$task->board->id, $task->id]) }}" method="POST" class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                @csrf
                @method('PUT')
                <div class="flex-shrink-0">

                    <div>
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="task">Загловок задачи</label>
                        <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" value="{{ $task->title }}" type="text" name="title">
                    </div>

                    <div class="mt-10">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="task">Описание задачи</label>
                        <p><textarea class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" rows="10" cols="45" name="description">{{ $task->description }}</textarea></p>
                    </div>

                    <div class="mt-10">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="task">Deadline</label>
                        <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" value="{{ $task->deadline }}" type="date" name="deadline">
                    </div>

                    <div class="mt-10">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="task">Status</label>
                        <select class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" name="status" size="1">
                            <option value="incomplete">Не готова</option>
                            <option value="completed">Готова</option>
                        </select>
                    </div>

                    <input type="hidden" name="board_id" value="{{ $task->board->id }}">

                    <button class="mt-10 py-2 px-4 font-semibold rounded-lg shadow-md text-white bg-green-500 hover:bg-green-700" type="submit">
                        Изменить
                    </button>

                </div>
            </form>
        </div>

    </div>

</x-app-layout>