routes/web.php
<?php

use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\ReminderController;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BoardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


// TODOList routes
Route::name('boards.')->prefix('boards')->group(function () {
    // Boards routes
    Route::get('/', [BoardController::class, 'index'])->name('index');
    Route::get('/create', [BoardController::class, 'create'])->name('create');
    Route::post('/', [BoardController::class, 'store'])->name('store');
    Route::get('/{id}/edit', [BoardController::class, 'edit'])->name('edit');
    Route::put('/{id}', [BoardController::class, 'update'])->name('update');
    Route::delete('/{id}', [BoardController::class, 'destroy'])->name('destroy');

    // Tasks routes
    Route::name('tasks.')->prefix('{board_id}/tasks')->group(function () {
        Route::get('/create', [TaskController::class, 'create'])->name('create');
        Route::post('/', [TaskController::class, 'store'])->name('store');
        Route::get('/{id}/edit', [TaskController::class, 'edit'])->name('edit');
        Route::put('/{id}', [TaskController::class, 'update'])->name('update');
        Route::delete('/{id}', [TaskController::class, 'destroy'])->name('destroy');
    });
});


// Reminder routes
Route::name('reminders.')->prefix('reminders')->group(function () {
    Route::get('/', [ReminderController::class, 'index'])->name('index');
});


// Calendar routes
Route::name('calendar.')->prefix('calendar')->group(function () {
   Route::get('/', [CalendarController::class, 'index'])->name('index');
});


// Profile routes
Route::name('profile.')->prefix('profile')->middleware('auth')->group(function () {
    Route::get('/', [RegisteredUserController::class, 'index'])->name('index');
    Route::get('/editNameAndEmail', [RegisteredUserController::class, 'editNameAndEmail'])->name('editNameAndEmail');
    Route::get('/editPassword', [RegisteredUserController::class, 'editPassword'])->name('editPassword');
    Route::put('/updatePassword', [RegisteredUserController::class, 'updatePassword'])->name('updatePassword');
    Route::put('/updateEmailAndName', [RegisteredUserController::class, 'updateNameAndEmail'])->name('updateNameAndEmail');
});

require __DIR__.'/auth.php';

app/Models/Board.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Board extends Model
{
    use HasFactory;

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function tasks()
    {
        return $this->hasMany(Task::class, 'board_id');
    }
}

app/Http/Controllers/BoardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Board;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BoardController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $user = Auth::user();
        return view('boards.index', ['boards' => $user->boards]);
    }

    public function create()
    {
        return view('boards.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:255',
                           ]);

        $board = new Board();
        $board->name = $request->input('name');
        $board->color = $request->input('color');
        $board->user_id = Auth::id();
        $board->save();

        return redirect()->route('boards.index');
    }

    public function edit($id)
    {
        $board = Board::find($id);
        return view('boards.edit', ['board' => $board]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required'
                           ]);

        $board = Board::find($id);
        $board->name = $request->input('name');
        $board->color = $request->input('color');
        $board->save();

        return redirect()->route('boards.index');
    }

    public function destroy($id)
    {
        $board = Board::find($id);
        $tasks = $board->tasks;
        foreach ($tasks as $task) {
            $task->delete();
        }
        $board->delete();

        return redirect()->route('boards.index');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/boards/create.blade.php
<x-app-layout>
    <x-slot name="header">
        Создание доски
    </x-slot>

    <div class="m-10 p-10 max-w-sm mx-auto bg-white rounded-xl shadow-md flex-column space-y-4 items-center space-x-4">

        <!--Ошибки ввода-->
        <div>
        @if ($errors->any())
            <div class="alert">
                <ul class="list-disc">
                    @foreach ($errors->all() as $error)
                        <li class="text-red-700">{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        </div>

        <div>
            <form action="{{ route('boards.store') }}" method="POST" class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                @csrf
                <div class="flex-shrink-0">

                    <div>
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="board">Навзвание доски</label>
                        <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" type="text" name="name" id="task-name">
                    </div>

                    <div class="mt-10">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="board">Цвет</label>
                        <select class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" name="color" size="1">
                            <option value="#E6E6FA">Белый</option>
                            <option value="#ADFF2F">Зелёный</option>
                            <option value="#00FFFF">Синий</option>
                        </select>
                    </div>

                    <button class="mt-10 py-2 px-4 font-semibold rounded-lg shadow-md text-white bg-green-500 hover:bg-green-700" type="submit">
                        Создать
                    </button>

                </div>
            </form>
        </div>

    </div>

</x-app-layout>

resources/views/boards/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        Изменение доски
    </x-slot>

    <div class="m-10 p-10 max-w-sm mx-auto bg-white rounded-xl shadow-md flex-column items-center space-y-4 space-x-4">

        <!--Ошибки ввода-->
        <div>
            @if ($errors->any())
                <div class="alert">
                    <ul class="list-disc">
                        @foreach ($errors->all() as $error)
                            <li class="text-red-700">{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>

        <div>
            <form action="{{ route('boards.update', $board->id) }}" method="POST" class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                @method('PUT')
                @csrf
                <div class="flex-shrink-0">

                    <div>
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="board">Навзвание доски</label>
                        <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" type="text" name="name" id="task-name" value="{{ $board->name }}">
                    </div>

                    <div class="mt-10">
                        <label class="p-5" for="board">Цвет</label>
                        <select class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" name="color" size="1">
                            <option value="#E6E6FA">Белый</option>
                            <option value="#ADFF2F">Зелёный</option>
                            <option value="#00FFFF">Синий</option>
                        </select>
                    </div>

                    <button class="mt-10 py-2 px-4 font-semibold rounded-lg shadow-md text-white bg-green-500 hover:bg-green-700" type="submit">
                        Изменить
                    </button>

                </div>
            </form>
        </div>

    </div>

</x-app-layout>

resources/views/boards/index.blade.php
<x-app-layout>
    <x-slot name="header">
        Мои доски
    </x-slot>

    <!--Кнопка создания доски-->
    <div class="m-5">
        <form method="GET" action="{{ route('boards.create') }}">
            @csrf
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded">
                Создать доску
            </button>
        </form>
    </div>


    <div class="m-5">
        @foreach($boards as $board)

            <!--Блок доски-->
            <div id="board_{{ $board->id }}" class="inline-flex mt-10 mr-10 p-10 max-w-sm mx-auto rounded-xl shadow-md flex-1 items-center space-y-4">
                <style>
                    #board_{{$board->id}} {
                        background-color: {{ $board->color }};
                    }
                </style>
                <div class="space-y-10">

                    <!--Имя доски-->
                    <div class="mb-10 font-bold text-3xl">
                        {{ $board->name }}
                    </div>

                    <!--Задачи доски-->
                    <div class="space-y-10">
                        @foreach($board->tasks as $task)
                            <div class="p-6 max-w-sm mx-auto bg-white rounded-xl shadow-md flex-column items-center space-y-4">

                                <!--Статус задачи-->
                                @if(!$task->isCompleted())
                                    <p class="text-xs text-gray-700">{{ $task->status }}</p>
                                @else
                                    <p class="text-lg text-green-700">{{ $task->status }}</p>
                                @endif

                                <!--Заголовок задачи-->
                                <div class="text-xl font-medium text-black">{{ $task->title }}</div>

                                <!--Описание задачи-->
                                <p class="text-gray-500">{{ $task->description }}</p>

                                <!--Deadline задачи-->
                                <div>
                                    <p class="text-red-500">Deadline: </p>
                                    <p><time>{{ $task->deadline }}</time></p>
                                </div>

                                <!--Дата исполнения задачи-->
                                    @if($task->isCompleted())
                                        <p class="text-green-500">Completed at: </p>
                                        <p><time>{{ $task->completion_date }}</time></p>
                                    @endif

                                <!--Кнопка удаления задачи-->
                                <div>
                                    <form method="POST" action="{{ route('boards.tasks.destroy', [$task->board_id, $task->id]) }}">
                                        @csrf
                                        @method('DELETE')
                                        <button class="bg-blue-500 hover:bg-red-700 text-white font-bold py-2 px-4 border rounded">
                                            Удалить
                                        </button>
                                    </form>
                                </div>

                                <!--Кнопка изменения задачи-->
                                <div>
                                    <form method="GET" action="{{ route('boards.tasks.edit', [$task->board_id, $task->id]) }}">
                                        @csrf
                                        <button class="bg-blue-500 hover:bg-red-700 text-white font-bold py-2 px-4 border rounded">
                                            Изменить
                                        </button>
                                    </form>
                                </div>

                                @if(!$task->isCompleted())

                                        <!--Кнопка напоминания задачи-->
                                        <div>
                                            <form method="POST" action="{{ route('boards.tasks.update', [$task->board_id, $task->id]) }}">
                                                @csrf
                                                @method('PUT')
                                                <input type="hidden" name="title" value="{{ $task->title }}">
                                                <input type="hidden" name="description" value="{{ $task->description }}">
                                                <input type="hidden" name="deadline" value="{{ $task->deadline }}">
                                                <input type="hidden" name="status" value="incomplete">
                                                @if($task->isSetReminder())
                                                    <input type="hidden" name="notify" value="false">
                                                    <button class="bg-blue-500 hover:bg-red-700 text-white font-bold py-2 px-4 border rounded">
                                                        Убрать напоминание
                                                    </button>
                                                @else
                                                    <input type="hidden" name="notify" value="true">
                                                    <button class="bg-blue-500 hover:bg-red-700 text-white font-bold py-2 px-4 border rounded">
                                                        Напомнить
                                                    </button>
                                                @endif
                                            </form>
                                        </div>

                                    @endif
                            </div>
                        @endforeach
                    </div>

                    <!--Кнопки управления-->
                    <div class="space-y-4">

                        <!--Кнопка создания задачи-->
                        <div>
                            <form method="GET" action="{{ route('boards.tasks.create', $board->id) }}">
                                @csrf
                                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded">
                                    Создать задачу
                                </button>
                            </form>
                        </div>

                        <!--Кнопка изменения доски-->
                        <div>
                            <form method="GET" action="{{ route('boards.edit', $board->id) }}">
                                @csrf
                                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded">
                                    Изменить доску
                                </button>
                            </form>
                        </div>

                        <!--Кнопка удаления доски-->
                        <div>
                            <form method="POST" action="{{ route('boards.destroy', $board->id) }}">
                                @csrf
                                @method('DELETE')
                                <button class="bg-blue-500 hover:bg-red-700 text-white font-bold py-2 px-4 border border-blue-700 rounded">
                                    Удалить доску
                                </button>
                            </form>
                        </div>

                    </div>

                </div>
            </div>
        @endforeach
    </div>

</x-app-layout>